// 자동 생성 파일: node tools/gen-parking.js
// board: 6x6 36글자 (o 빈칸, x 벽, A 빨간 차, B~ 다른 차), min: 검증된 최소 이동 수
window.PARKING_LEVELS = [
  {"board":"oIIoooGCCDEEGAADoFGJJDoFoBBoHHoooooo","min":4},
  {"board":"oooJCoBBBJCooAAoFoDEEoFIDGGKKIHHHooo","min":5},
  {"board":"oGBBIIoGoooEAAoooEooDooHooDCCHooooFF","min":6},
  {"board":"GooooDGCooFDoCAAFIoCoBBIKKoHoIEEoHJJ","min":7},
  {"board":"HHHCCoBBIDooAAIDoooGGoooooEEooFFJJoo","min":5},
  {"board":"oDoEEIoDoHBIAAoHBoKJoFFFKJGCCoooGooo","min":8},
  {"board":"ooKHHHCCKGoooAAGEooBDDEooBJJooIIooFF","min":9},
  {"board":"KooIIoKoCDHoAACDHooBGGFooBJoFoooJoEE","min":10},
  {"board":"BBooCoooooCoAAooCIHHGGoIFEEoDDFooooo","min":11},
  {"board":"ooEoCoooEFCHAAKFoHIoKooGIJJoBGoDDDBo","min":13},
  {"board":"EEoooJoIIHHJooAAoJCCBoooFoBoDDFGGGKK","min":10},
  {"board":"oIIIFoJJJGFKAAoGFKCooHHoCoDDDoCoBBEE","min":11},
  {"board":"DoEELLDKKJBBDAAJHCMMoJHCoFFGGooooIIo","min":12},
  {"board":"JBoGGKJBFoHKAAFIHDoooIHDoooCoDEEoCoo","min":14},
  {"board":"KKKoEoDoooEoDAACEoDoJCFFHGJooIHGoBBI","min":10},
  {"board":"oJFFCooJHHCoIAADBEIoKDBEooKGoooooGoo","min":15},
  {"board":"GoHHKKGoooCCAAFooDIIFoBDoJJJBDooooEE","min":16},
  {"board":"ooDKKoooDoooJoAABGJIIFBGJoHFCCEEHFoo","min":17},
  {"board":"KoGGEoKoCoEoAACoFHLLIIFHBBBDoJoooDoJ","min":18},
  {"board":"oooDBoLJJDBGLoAABGEHoooKEHMCCKIIMoFF","min":20},
  {"board":"oCJHHDoCJEoDAAJEooIoGGGoIooBBxIFFooo","min":14},
  {"board":"oooxBBxDDCJoKAACJIKooooIKGHFFIoGHEEo","min":16},
  {"board":"LMMoxELGGGJEFAAoJEFIoBHHFIoBKKoCCCDD","min":17},
  {"board":"GGooIIooxoLLAAKCoMEEKCBMFHHDBoFJJDoo","min":19},
  {"board":"BooFIIBoJFKoAAJEKDCCCEoDooxooGoooHHG","min":15},
  {"board":"oxIIoxGGBBHoAACEHoooCEKKJooFFDJooooD","min":20},
  {"board":"ooCFFFIICGEooAAGEoHoDDExHBoKKooBoJJo","min":22},
  {"board":"EEEJJBFFGLLBAAGooIHHoxDICoMMDoCxoKKo","min":23},
  {"board":"EEEGIHLLMGIHAAMooJDoBBoJDoFFxJKKooCC","min":25},
  {"board":"ooxEJJooMEIIAAMooCLBBooCLFFoKHDDGGKH","min":28}
];
